name: ENV Variables 
on: push 

jobs: 
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone infra
        run: |
          git clone https://${{ github.token }}@github.com/msanchez-calimaco/tf-wordpress-infrastructure.git
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"