name: ENV Variables 
on: push 

jobs: 
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: msanchez-calimaco/tf-wordpress-infrastructure
          path: production
  